### ISSUE TITLE
Incompatible with Stylish add-on

### ISSUE THREAD

**Issue by HyphenSam** [cluclead/facebook-disconnect#2]
When this add-on is enabled, [I can't write any new styles using Stylish](http://i.imgur.com/1ABkFAo.png).
If the add-on is disabled, [I can now write again](http://i.imgur.com/QsVfJqY.png).
A nice way to fix this is to add a whitelist to certain urls/domains.

**Comment by adamhotep** [comment]
@HyphenSam: is this still an issue for you?  (I'm not a dev, just interested.)

As a workaround, you could consider a user script using [Greasemonkey](http://www.greasespot.net/) or [Tampermonkey](https://tampermonkey.net/) and add your CSS inside [GM_addStyle](https://wiki.greasespot.net/GM_addStyle) like this:



    // ==UserScript==
    // @name        My Website - Additional CSS
    // @namespace   https://example.com/my_website
    // @include     http://example.com/target_site
    // @version     1
    // @grant       GM_addStyle
    // ==/UserScript==
    
    GM_addStyle(`

      /* put CSS here */

    `);

Stylish's [UserStyles.org](https://userstyles.org) site even has "Install style as userscript" links for each style hosted there.
